### ISSUE TITLE
Error messages displayed on the front end

### ISSUE THREAD

**Issue by noctividus** [johnstray/gs-blog#127]
This plugin seems to now put error messages all over the front end. Error messages, or meaningless update messages should never be presented to the user on the frontend. 

To remove them, I placed this in my theme's css:

.updated{
	display: none;
}

or

.error{
	display: none;
}

**Comment by johnstray** [comment]
I'll have to look into this one. I agree that that should not occur.

**Comment by johnstray** [comment]
This will be fixed in #128.
