### ISSUE TITLE
php error in Custom Fields Manager

### ISSUE THREAD

**Issue by pigsound** [johnstray/gs-blog#138]
### Expected behaviour
show settings form

### Actual behaviour
blank;
debugger reports:
"Fatal error: Uncaught Error: Cannot use string offset as an array in C:\MAMP\htdocs\directory\plugins\gs-blog\class\customFields.php:25 Stack trace: #0 C:\MAMP\htdocs\directory\plugins\gs-blog\inc\manage_custom_fields.php(10): customFields->getCustomFields() #1 C:\MAMP\htdocs\directory\plugins\gs-blog\inc\adminFunctions.php(89): show_custom_fields() #2 C:\MAMP\htdocs\directory\admin\load.php(39): blog_admin_controller() #3 {main} thrown in C:\MAMP\htdocs\directory\plugins\gs-blog\class\customFields.php on line 25"

**Comment by johnstray** [comment]
This appears to be a compatibility issue with PHP 7 as far as I can tell. 

This class has never been modified by me before, but I will investigate was to update it for compatibility.

**Comment by webservsol** [comment]
$cf = array('options' => array(), 'main' => array()); Line 17 will solve the issue

**Comment by johnstray** [comment]
Thanks @webservsol. That worked perfectly to fix the error.
