### ISSUE TITLE
Doubled backslashes in blog posts

### ISSUE THREAD

**Issue by toma315** [johnstray/gs-blog#161]
### Expected behaviour

Create a post with backslashes in text. Save the post. Edit the post. Save the post. Number of backslashes is supposed to not be increasing.

### Actual behaviour

Backslashes are doubled each time you open a post.

### Steps to reproduce the behaviour

see above

### Suggested patch

Patch against 3.4.4 included.

[backslash.txt](https://github.com/johnstray/gs-blog/files/3039889/backslash.txt)

**Comment by johnstray** [comment]
Thanks for you patch @toma315. It will be added in the next release. 
Apologies it's taken so long to respond to this, I haven't had the time to work on this for quite a while.
