### ISSUE TITLE
gs-blog plugin shuts down after clicking on blog tab

### ISSUE THREAD

**Issue by pigsound** [johnstray/gs-blog#162]
### Expected behaviour
clicking on the blog tab in the backend should open the blog editor and settings tabs for creating and editing a blog entry

### Actual behaviour
clickng blog tab opens a page with no blog interface. blog tab disappears and in gs-blog is deactivated in plugins

### Steps to reproduce the behaviour
install latest getsimple cms 3.3.16. install gs-blog plugin. activate plugin. click on blog tab (with getsimple 3.3.15 this problem does not occur)

**Comment by johnstray** [comment]
Hi @pigsound. This is most commonly caused by a php error. Could you please enable showing of php errors on your web server, try loading the page again, then report back here with the php error that outputs. Note: you may also need to enable debug mode in GetSimple.

**Comment by johnstray** [comment]
Apologies it's taken almost a whole year to respond to this. I haven't had the time to be able to work on this for quite a while.

**Comment by johnstray** [comment]
__PHP Fatal error__: Uncaught TypeError: count(): Argument ($var) must be of type Countable, bool given in _/gs-blog/inc/html/posts-admin.php:62_

This is caused by the `$Blog->listPosts` class method returning false when no posts instead of an empty array.
