### ISSUE TITLE
Hierarchical URL Issue

### ISSUE THREAD

**Issue by bensayersllc** [johnstray/gs-blog#51]
Hello, I'm trying out your GS Blog plugin and I'm having some trouble with the post URLs. I'm a big fan of mvlcek's plugins and I'm using his i18n Navigation plugin to support Hierarchical URL's but when I create a new post in GS Blog, the URL shows the %parents% placeholder - like this: http://www.mydomain.com/%parents%/blog/post/post-title

I also noticed the post URL doesn't include the trailing slash (/). Do you know if there's a way to fix these two issues? I'm new to PHP so any help you can offer would be most appreciated! Here's the info from mvlcek's website, I always have nested/child pages in the websites I build, so I'll need these plugins to work together. I usually use i18n Special Pages to create Blogs but would definitely prefer to use a real solution like you have here. Thanks!

<blockquote><em>HIERARCHICAL URLS (<a href="http://mvlcek.bplaced.net/get-simple/i18n" target="_blank">SEEN HERE</a>)
Since version 3.2 you can use the placeholder %parents% in your fancy URL in order to include all ancestors of your page and not just the immediate parent.</em></blockquote>

**Comment by johnstray** [comment]
Thanks for your comment and request. I'll have a look at it this weekend and see what I can come up with.

**Comment by bensayersllc** [comment]
Thanks John!

**Comment by johnstray** [comment]
This issue was caused by function 'get_blog_url' using the GS built-in 'find_url' function. I've now added an IF statement that will check if the 'find_i18n_url' function is available and use it instead, but defaults back to the standard 'find_url' if the i18n plugin is not installed.

Initial testing shows that this fix has resolved the issue.

**Comment by bensayersllc** [comment]
Excellent, thanks John. Will the item be updated on GS Extend
<http://get-simple.info/extend/plugin/getsimple-blog/810/>? LMK and I'll
give it a shot - thanks again!

[image: Ben Sayers LLC] <http://www.bensayers.net/>Ben Sayers
Cell: 517-404-0270
Web: www.bensayers.netFreelance Web/Graphic Design & Development

**Comment by johnstray** [comment]
Yes, this fix and a few others when I get round to them will be released in the next update on Extend.
