### ISSUE TITLE
duble lang variables

### ISSUE THREAD

**Issue by nok3s** [johnstray/gs-blog#60]
Language files:
Line 150 & 154 are the same language variables "POST_THUMBNAIL_LABEL"

**Comment by nok3s** [comment]
ADDED VERSION 1.1.4 & ADDED VERSION 1.1.5
- CSS_SETTINGS double

ADDED VERSION 1.1.6
- RSS_FEED

**Comment by johnstray** [comment]
Please use the existing issue #59 whilst initially translating and repairing the language file.
