### ISSUE TITLE
Changed layout of Polish language file

### ISSUE THREAD

**Issue by johnstray** [johnstray/gs-blog#63]
The layout of the language file have been changed. All unused strings have been removed and the file has been cleaned up to look much neater. Some minor changes have been made to a few of the strings.

Could you please re-translate the new language files. The old language files are available in the /gs-blog/lang/old/ directory for you reference.

**Comment by Every0ne** [comment]
about 50% left. Will be done tomorrow.

**Comment by johnstray** [comment]
Thanks mate

**Comment by johnstray** [comment]
New string added. Have a look at line 204.

**Comment by johnstray** [comment]
Never mind. New string already exists.

**Comment by Every0ne** [comment]
Done.
