### ISSUE TITLE
Changed layout of French language file

### ISSUE THREAD

**Issue by johnstray** [johnstray/gs-blog#65]
The layout of the language file have been changed. All unused strings have been removed and the file has been cleaned up to look much neater. Some minor changes have been made to a few of the strings.

Could you please re-translate the new language files. The old language files are available in the /gs-blog/lang/old/ directory for you reference.

**Comment by johnstray** [comment]
Where have my translators gone? This update is well overdue now simply because they've disappeared.

@jeckyl or @madvik, Where are you?

**Comment by gschintgen** [comment]
Hi, I've got a question concerning html entities: which characters should be encoded as html entities and which can be kept as utf-8 characters? In lang/old/de_DE.php all letters with umlauts (ä, ö, etc.) are coded as html entities, whereas the accented characters in lang/old/fr_FR.php were coded as is (i.e. plain utf-8 characters: é, à, etc.). Is utf-8 fine or should the language files be kept encoding-independent?

**Comment by johnstray** [comment]
Utf-8 is fine. Just using hymn entities for apostrophes to that escape characters didn't have to be used.

**Comment by johnstray** [comment]
Everything appears to be ok in this one now, so I will close this issue.
