### ISSUE TITLE
Changed layout of German language file

### ISSUE THREAD

**Issue by johnstray** [johnstray/gs-blog#66]
The layout of the language file have been changed. All unused strings have been removed and the file has been cleaned up to look much neater. Some minor changes have been made to a few of the strings.

Could you please re-translate the new language files. The old language files are available in the /gs-blog/lang/old/ directory for you reference.

**Comment by johnstray** [comment]
Where have my translators gone? This update is well overdue now simply because they've disappeared.

@nok3s, Where are you?

**Comment by nok3s** [comment]
Sorry, in a few days I will continue

**Comment by johnstray** [comment]
@nok3s, still awaiting the finished language file. I'd like to release this update within the next week please. Thanks.

**Comment by johnstray** [comment]
Thanks for your work on this @gschintgen!
