### ISSUE TITLE
Call to undefined function auto_import_thumbnail()

### ISSUE THREAD

**Issue by Axisar** [johnstray/gs-blog#70]
Call to undefined function auto_import_thumbnail() in debug mod. with no debug, just blank screen in autorssupdater

**Comment by johnstray** [comment]
Thanks for the heads up. I'll check it out. 

Could you please have a look at your logs in GetSimple and/or your server and let me know in which file and on what line the error was triggered.

**Comment by Axisar** [comment]
its right inside rssAutoImporter.php, line 53. maybe i`m doing something wrong, but seems this function mentioned one time in whole code.

**Comment by johnstray** [comment]
Ok, looks like I've forgotten to write the function that is being called. Whoops. 

Not sure if I'm going to include thumbnail support in this last update; I probably won't. I think it's something that I will do in the new blog plugin I'm working on. 

So, I'll fix that either way ready for this last update.
