### ISSUE TITLE
Add post counts for categories

### ISSUE THREAD

**Issue by johnstray** [johnstray/gs-blog#74]
Add a method for enabling post counts in Category lists.

I will probably add this to the show_blog_categories() function using a setting to enable/disable.

**Comment by johnstray** [comment]
There are reports of this not working. I'll have to have a look to see what is going wrong.

**Comment by gschintgen** [comment]
Hi, I'm getting lots of php warnings when using <?php show_blog_categories(true,true); ?>

Warning: Illegal offset type in /var/www/gsblogtest/plugins/gs-blog/inc/frontEndFunctions.php on line 195.

I'm using 3.4.1 (or "master", can't remember, they should be almost identical.)
Unfortunately I can't compare to older versions of show_blog_categories, it's the first time I wanted to use it.

**Comment by gschintgen** [comment]
found the issue:
Line 195 should read
`$post_array[$slug] = $file;`
instead of
`$post_array[$data->slug] = $file;`

**Comment by johnstray** [comment]
Hmmm... That change should of been in that commit.
