### ISSUE TITLE
3.4.0: broken de_DE / fr_FR translation :-(

### ISSUE THREAD

**Issue by gschintgen** [johnstray/gs-blog#75]
getsimple breaks, when de_DE is active.
I'll fix it right away! Sorry.

**Comment by johnstray** [comment]
Already fixed. Was a missing comma on line 28.

**Comment by johnstray** [comment]
Thanks. I fixed one already, but didn't see those ones.

**Comment by johnstray** [comment]
It was reported on the GetSimple forum that the German language file had less lines than the rest of the languages. I've had a look and discovered that there were 9 missing strings. I have now added these strings to the file, but they will need translating. @gschintgen could you please do those translations when you go over this file please.

**Comment by johnstray** [comment]
@gschintgen: please check and fix line 137 of de_DE.php then I can close this issue.

**Comment by johnstray** [comment]
@gschintgen, You've done well. Thank-you!
