### ISSUE TITLE
Internationalisation shouldn't adjoin i18n-strings to create text or headings.

### ISSUE THREAD

**Issue by gschintgen** [johnstray/gs-blog#76]
For example, the heading "Manage custom fields" is apparently (I didn't check the code) created by concatenating MANAGE and CUSTOM_FIELDS_BUTTON.

This is fine for en_US/GB but incorrect for de_DE due to a different word order. Currently the generated heading is "Verwaltung benutzerdefinierte Felder" which is grammatically improper. It should be "Verwaltung benutzerdefinierter Felder" (with an 'r') or "Benutzerdefinierte Felder verwalten" or "Verwaltung der benutzerdefinierten Felder", none of which can be expressed by the current i18n-strings.

For now it's okay/good enough, but for future new strings I'd recommend using distinct i18n-strings for similar situations. Or separate the action verb with a colon: "Manage: " + "custom fields".

**Comment by johnstray** [comment]
I'll have a look at the code a bit later, but as far as I know, CUSTOM_FIELDS_BUTTON should be separate from MANAGE. If not, I'll change the code so that it is. What your saying makes perfect sense.

**Comment by gschintgen** [comment]
Actually, it's CUSTOM_FIELDS that is appended to MANAGE. (line 13 of inc/manage_custom_fields.php)
