### ISSUE TITLE
incorrect string reference in html/settings-rss.php ?

### ISSUE THREAD

**Issue by gschintgen** [johnstray/gs-blog#77]
Hi,

In the rss settings part of the admin interface the current code labels one of the radio buttons {gs-blog/RSS_CONTENT}

I think there's something wrong in settings-rss.php, lines 30-35:
The code references RSS_CONTENT which no longer exists in the new lang files.
Furthermore RSS_DESCRIPTION should actually be some not yet defined RSS_SUMMARY string.
That's at least my understanding of what this section should actually do based on the information provided by the RSS_CONTENT_DESCRIPTION string.
(I haven't yet used or tried the RSS auto-importer)

**Comment by johnstray** [comment]
There were some incorrect language string references used on the RSS Auto Importer Settings page. As a result of this fix, 2 new strings were created and 2 others were modified.

Translators, please check you language files, update them as required, then remove the trailing comments before upload. Thanks
