### ISSUE TITLE
layout-listBefore.php not used when browsing by tag

### ISSUE THREAD

**Issue by gschintgen** [johnstray/gs-blog#81]
When I browse my blog by tags (i.e. clicking on a tag in the normal main blog page), the thumbnail isn't scaled correctly. I didn't have a closer look at the code, but I'd guess that the code from layout-listBefore.php isn't being included.

**Comment by johnstray** [comment]
I see what you mean. I need to add the includes to the functions that are missing this; archives, tags, categories.

**Comment by johnstray** [comment]
- [ ] show_blog_category()
- [ ] show_blog_archive()
- [ ] show_blog_tag()
- [ ] search_posts()
