### ISSUE TITLE
i18n: incomplete internationalisation (Post Options)

### ISSUE THREAD

**Issue by gschintgen** [johnstray/gs-blog#82]
When adding a new post, the "Post Options" are not translated, even though all translatable strings are present (in de_DE for example). The corresponding page options in the main GetSimple interface are correctly translated.

**Comment by johnstray** [comment]
This is a result of using the CustomFields Manager. The workaround for this is to modify the labels as required under the CustomFields Manager.

**Comment by johnstray** [comment]
Found a way to fix this! Refer to Issue #154 for details.
