### ISSUE TITLE
show_blog_post should output a "read more" link if excerpt==true

### ISSUE THREAD

**Issue by gschintgen** [johnstray/gs-blog#85]
Currently, only show_blog_recent_posts shows a "read more" link when it's working with excerpts. This should also be the case for the main blog page, where the html is generated by show_blog_post in conjunction with create_excerpt.

**Comment by johnstray** [comment]
Since this is not a user function, no options can be provided. If you want a read more link, modify `layout-list.php` to suit your needs.

**Comment by johnstray** [comment]
Adding this to this layout-list.php file by popular demand.
